/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 03 07:54:11 GMT 2020
 */

package jp.ac.kyoto_su.ise.compressor;

import org.junit.Test;
import static org.junit.Assert.*;
import jp.ac.kyoto_su.ise.compressor.NoCompressorException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class NoCompressorException_ESTest extends NoCompressorException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NoCompressorException noCompressorException0 = new NoCompressorException("*WF(\"~^CW");
  }
}
