/**
 * Scaffolding file used to store all the setups needed to run
 * tests automatically generated by EvoSuite
 * Wed Jun 03 07:55:52 GMT 2020
 */

package jp.ac.kyoto_su.ise.compressor;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ZlibCompressor_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() {
    org.evosuite.runtime.RuntimeSettings.className = "jp.ac.kyoto_su.ise.compressor.ZlibCompressor";
    org.evosuite.runtime.GuiSupport.initialize();
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {}
  }

  @AfterClass
  public static void clearEvoSuiteFramework(){
    Sandbox.resetDefaultSecurityManager();
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
  }

  @Before
  public void initTestCase(){
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
    setSystemProperties();
    org.evosuite.runtime.GuiSupport.setHeadless();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    org.evosuite.runtime.agent.InstrumentingAgent.activate();
  }

  @After
  public void doneWithTestCase(){
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
    org.evosuite.runtime.classhandling.JDKClassResetter.reset();
    resetClasses();
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
  }

  public static void setSystemProperties() {

    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    java.lang.System.setProperty("file.encoding", "UTF-8");
    java.lang.System.setProperty("java.awt.headless", "true");
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/pf/nrjdx0cd66372w5qflj318f40000gn/T/");
    java.lang.System.setProperty("user.country", "JP");
    java.lang.System.setProperty("user.dir", "/Users/okamototaku/M\u30BB\u30E1\u30B9\u30BF\u30FC1/compressor/compressor");
    java.lang.System.setProperty("user.home", "/Users/okamototaku");
    java.lang.System.setProperty("user.language", "ja");
    java.lang.System.setProperty("user.name", "okamototaku");
    java.lang.System.setProperty("user.timezone", "Asia/Tokyo");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ZlibCompressor_ESTest_scaffolding.class.getClassLoader() ,
      "jp.ac.kyoto_su.ise.compressor.NoCompressorException",
      "jp.ac.kyoto_su.ise.compressor.Compressor",
      "jp.ac.kyoto_su.ise.compressor.ZlibCompressor"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException {
    mock(Class.forName("java.io.InputStream", false, ZlibCompressor_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("java.io.OutputStream", false, ZlibCompressor_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("java.util.Enumeration", false, ZlibCompressor_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ZlibCompressor_ESTest_scaffolding.class.getClassLoader());

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "jp.ac.kyoto_su.ise.compressor.ZlibCompressor",
      "jp.ac.kyoto_su.ise.compressor.NoCompressorException",
      "jp.ac.kyoto_su.ise.compressor.BZip2Compressor"
    );
  }
}
