/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 03 07:55:01 GMT 2020
 */

package jp.ac.kyoto_su.ise.compressor;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.InputStream;
import java.io.OutputStream;
import jp.ac.kyoto_su.ise.compressor.ZlibCompressor;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;


@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true)
public class ZlibCompressor_ESTest extends ZlibCompressor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ZlibCompressor ZlibCompressor0 = new ZlibCompressor();
      InputStream inputStream0 = mock(InputStream.class, new ViolatedAssumptionAnswer());
      doReturn((-315), (-315), (-1)).when(inputStream0).read();
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      ZlibCompressor0.compress(inputStream0, outputStream0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ZlibCompressor ZlibCompressor0 = new ZlibCompressor();
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try {
        ZlibCompressor0.compress((InputStream) null, outputStream0);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("jp.ac.kyoto_su.ise.compressor.Compressor", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ZlibCompressor ZlibCompressor0 = new ZlibCompressor();
      String string0 = ZlibCompressor0.renameFile("");
      assertEquals(".zlib", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ZlibCompressor ZlibCompressor0 = new ZlibCompressor();
      InputStream inputStream0 = mock(InputStream.class, new ViolatedAssumptionAnswer());
      doReturn(0, 0, 0, 0, 0).when(inputStream0).read();
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      ZlibCompressor0.compress(inputStream0, outputStream0);
  }
}
